In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import os
import seaborn as sns
import sys
sys.path.append("/extdata4/baeklab/Hyeonseo/m6A/modformer")
from utils.utils import printmessage
import glob
import tqdm
import gc

In [2]:
block_ON0099_df = pd.read_pickle(f"/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0099/result/dorado-070/intermediates/block_df.pkl")
print(block_ON0099_df)

          cb_idx  start_pos  end_pos  pos_RM  penalty     score  \
0              2        165      186     175        6  0.857143   
1              1        220      241     230        9  0.785714   
2              2        247      268     257        0  1.000000   
3              0        452      473     462        0  1.000000   
4              1        478      499     488        3  0.928571   
...          ...        ...      ...     ...      ...       ...   
77735403       2          9       30      19       10  0.761905   
77735404       2          5       26      15        9  0.785714   
77735405       0          9       30      19        4  0.904762   
77735406       1         14       35      24       10  0.761905   
77735407       1         12       33      22       15  0.642857   

                                       read_id  total_score  \
0         626a5a68-924d-4cde-96ad-1e1fa86ccf62    19.142857   
1         626a5a68-924d-4cde-96ad-1e1fa86ccf62    19.142857   
2     

In [4]:
score_ON0099 = block_ON0099_df["score"].values
np.save("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0099/result/dorado-070/intermediates/score.npy", score_ON0099)
del block_ON0099_df
gc.collect()
print(score_ON0099)

[0.85714286 0.78571429 1.         ... 0.9047619  0.76190476 0.64285714]


In [5]:
block_ON0098_df = pd.read_pickle(f"/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0098/result/dorado-070/intermediates/block_df.pkl")
print(block_ON0098_df)


          cb_idx  start_pos  end_pos  pos_RM  penalty     score  \
0              1          5       26      15        7  0.833333   
1              1         86      107      96        7  0.833333   
2              2        113      134     123        2  0.952381   
3              0        147      168     157        8  0.809524   
4              1        173      194     183        2  0.952381   
...          ...        ...      ...     ...      ...       ...   
70833004       2          8       29      18        0  1.000000   
70833005       2          9       30      19        9  0.785714   
70833006       2          9       30      19        9  0.785714   
70833007       0          4       25      14       12  0.714286   
70833008       2          8       29      18       13  0.690476   

                                       read_id  total_score  \
0         8453a68c-1981-467b-96d9-e0f10bd80307    27.214286   
1         8453a68c-1981-467b-96d9-e0f10bd80307    27.214286   
2     

In [6]:
score_ON0098 = block_ON0098_df["score"].values
np.save("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0098/result/dorado-070/intermediates/score.npy", score_ON0098)
del block_ON0098_df
gc.collect()
print(score_ON0098)

[0.83333333 0.83333333 0.95238095 ... 0.78571429 0.71428571 0.69047619]


In [7]:
block_ON0093_df = pd.read_pickle(f"/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0093/ON0093/result/dorado-070/intermediates/block_df.pkl")
print(block_ON0093_df)

          cb_idx  start_pos  end_pos  pos_RM  penalty     score  \
0              1         13       34      23        9  0.785714   
1              2         40       61      50        3  0.928571   
2              2        124      145     134        0  1.000000   
3              1        252      273     262        8  0.809524   
4              1        431      452     441        7  0.833333   
...          ...        ...      ...     ...      ...       ...   
57078601       2          8       29      18       10  0.761905   
57078602       2          7       28      17       10  0.761905   
57078603       2          4       25      14       15  0.642857   
57078604       2          7       28      17       12  0.714286   
57078605       2          6       27      16       15  0.642857   

                                       read_id  total_score  \
0         c9c22acf-01fb-491b-aaa6-e7623556c32d    17.547619   
1         c9c22acf-01fb-491b-aaa6-e7623556c32d    17.547619   
2     

In [8]:
score_ON0093 = block_ON0093_df["score"].values
np.save("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0093/ON0093/result/dorado-070/intermediates/score.npy", score_ON0093)
del block_ON0093_df
gc.collect()
print(score_ON0093)


[0.78571429 0.92857143 1.         ... 0.64285714 0.71428571 0.64285714]


In [9]:
block_ON0092_df = pd.read_pickle(f"/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0092/ON0092/result/dorado-070/intermediates/block_df.pkl")
print(block_ON0092_df)

           cb_idx  start_pos  end_pos  pos_RM  penalty     score  \
0               2         24       45      34        2  0.952381   
1               0         57       78      67        0  1.000000   
2               1         84      105      94        0  1.000000   
3               2        111      132     121        0  1.000000   
4               0        144      165     154        0  1.000000   
...           ...        ...      ...     ...      ...       ...   
128973864       2          5       26      15       12  0.714286   
128973865       2          9       30      19        6  0.857143   
128973866       2          8       29      18       15  0.642857   
128973867       1          9       30      19       12  0.714286   
128973868       1          8       29      18       15  0.642857   

                                        read_id  total_score  \
0          f2667780-9131-4827-8c8e-a26b25b51fa1    33.404762   
1          f2667780-9131-4827-8c8e-a26b25b51fa1    33.4

In [10]:
score_ON0092 = block_ON0092_df["score"].values
np.save("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0092/ON0092/result/dorado-070/intermediates/score.npy", score_ON0092)
del block_ON0092_df
gc.collect()
print(score_ON0092)


[0.95238095 1.         1.         ... 0.64285714 0.71428571 0.64285714]


In [11]:
block_ON0096_df = pd.read_pickle(f"/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0096/result/dorado-070/intermediates/block_df.pkl")
print(block_ON0096_df)

           cb_idx  start_pos  end_pos  pos_RM  penalty     score  \
0               1         19       40      29        0  1.000000   
1               2         46       67      56        0  1.000000   
2               0         79      100      89        0  1.000000   
3               1        106      127     116        0  1.000000   
4               2        133      154     143        0  1.000000   
...           ...        ...      ...     ...      ...       ...   
177948227       2          6       27      16        9  0.785714   
177948228       2          8       29      18       12  0.714286   
177948229       2          6       27      16        5  0.880952   
177948230       2          7       28      17        2  0.952381   
177948231       2          9       30      19       12  0.714286   

                                        read_id  total_score  \
0          93e7d60b-ddf6-4c2c-b368-8fec673dce94    37.023810   
1          93e7d60b-ddf6-4c2c-b368-8fec673dce94    37.0

In [12]:
score_ON0096 = block_ON0096_df["score"].values
np.save("/extdata4/baeklab/Hyeonseo/m6A/runs/exp_BB87/ON0096/result/dorado-070/intermediates/score.npy", score_ON0096)
del block_ON0096_df
gc.collect()
print(score_ON0096)

[1.         1.         1.         ... 0.88095238 0.95238095 0.71428571]


In [13]:
df  = pd.read_csv("/extdata3/baeklab/Hyeonseo/m6A/res/m6asites/m6A_Jungmin_110823.txt", sep="\t")

In [16]:
print(df)

         chr str       pos  SAC GLORI MICLIP2 M6ACE     DoM_1     DoM_2
0       chr1   +    923969   no   yes     yes    no  0.206522  0.172414
1       chr1   +    924018   no   yes     yes    no  0.240000  0.181818
2       chr1   +    924037   no   yes      no    no  0.402778  0.409091
3       chr1   +    924098   no   yes     yes   yes  0.605691  0.625000
4       chr1   +    924136   no   yes     yes   yes  0.753036  0.768340
...      ...  ..       ...  ...   ...     ...   ...       ...       ...
663824  chrY   +  12915176  yes    no      no    no  0.000000  0.000000
663825  chrY   +  12918210   no   yes      no    no  0.650000  0.565217
663826  chrY   +  20760028   no   yes      no    no  0.142857  0.133333
663827  chrY   -  19707564   no   yes      no    no  1.000000  0.636364
663828  chrY   -  19707960  yes    no      no    no  0.000000  0.000000

[663829 rows x 9 columns]


In [17]:
print(np.sum(df["SAC"]=="yes"))
print(np.sum(df["GLORI"]=="yes"))
print(np.sum(df["MICLIP2"]=="yes"))
print(np.sum(df["M6ACE"]=="yes"))


208313
266101
239867
122738


In [18]:
print(np.mean([208313,
               266101,
               239867,
               122738,]))

209254.75
